### ISSUE TITLE
Upgrade to logstash 5

### ISSUE THREAD

**Issue by jasonkuhrt** [pires/docker-logstash#1]
If you don't, you cannot use Kibana 4 which is radically different/better than kibana 3.

https://github.com/elasticsearch/kibana/issues/2513

**Comment by pires** [comment]
To be honest, I don't want this project to include non-final releases of such software. It would eventually bring issues that I can't give support to. I'd say you're free to adapt as needed for your projects ;-)

**Comment by jasonkuhrt** [comment]
Fair enough : )
